name: action test
on:
  push:
    branches:
      - main # 针对的是main分支的push事件
    paths:
      - ".github/workflows/*" # 仅当此文件发生变化时触发
      - "README.md" # 也可以添加其他文件或目录
      - "src/**" # 监控src目录下的所有文件变化
      - "bin/**" # 监控bin目录下的所有文件变化
      - "package.json" # 监控package.json文件变化

jobs:
  test:
    runs-on: ubuntu-latest # 使用最新的Ubuntu环境

    steps:
      - uses: actions/checkout@v2 # 检出代码

      - name: ssh id_rsa # 设置id_rsa
        # 创建.ssh目录
        # 将私钥写入文件
        # 设置私钥权限
        # 添加服务器的公钥到known_hosts
        run: |
          mkdir -p ~/.ssh 
          echo "${{ secrets.MY_ID_RSA}}" > ~/.ssh/id_rsa 
          chmod 600 ~/.ssh/id_rsa 
          ssh-keyscan 106.55.145.191 >> ~/.ssh/known_hosts

      - name: deploy # 部署到服务器
        run: |
          ssh root@106.55.145.191

          # 注意：服务器已git clone代码到 /myblog/imooc-320-server
          # 这里假设服务器上已经有了代码仓库，并且在main分支上
          # 如果没有，可以先在服务器上执行 git clone

          # mkdir -p myblog-test
          # cd myblog-test
          # git clone https://github.com/ltog1/imooc-320-server.git
          # cd imooc-320-server
          # git checkout .
          # git checkout main
          # git pull origin main
          # npm install
          # npm install -g pm2
          # npm run prd
        
          sudo mkdir -p /myblog-test
          sudo chown $USER: /myblog-test
          echo "文件夹路径：$(realpath /myblog-test)"

      - name: delete id_rsa # 删除id_rsa
        run: |
          rm -rf ~/.ssh/id_rsa
          rm -rf ~/.ssh/known_hosts
